using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Reflection;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using System.Collections.Generic;
using VerifyCS = DependencyInjection.SourceGenerator.LightInject.Tests.CSharpSourceGeneratorVerifier<DependencyInjection.SourceGenerator.LightInject.DependencyInjectionRegistrationGenerator>;
using Microsoft.CodeAnalysis.Testing;

namespace DependencyInjection.SourceGenerator.LightInject.Tests;

public class DependencyInjectionRegistrationGeneratorTests
{
    private static readonly string _header = """
        // <auto-generated/>
        #pragma warning disable
        #nullable enable
        namespace DependencyInjection.SourceGenerator.LightInject.Demo;
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        
        """;

    private readonly ImmutableArray<string> _references = AppDomain.CurrentDomain
    .GetAssemblies()
    .Where(assembly => !assembly.IsDynamic)
    .Select(assembly => assembly.Location)
    .ToImmutableArray();

    private async Task RunTestAsync(string code, string expectedResult, params (string HintName, string Content)[] additionalGeneratedSources)
    {
        var net8 = new ReferenceAssemblies(
                    "net8.0",
                    new PackageIdentity(
                        "Microsoft.NETCore.App.Ref",
                        "8.0.0"),
                    Path.Combine("ref", "net8.0"));

        var generatedSources = new List<(Type, string, SourceText)>
        {
            (typeof(DependencyInjectionRegistrationGenerator), "CompositionRoot.g.cs", SourceText.From(expectedResult, Encoding.UTF8))
        };

        foreach (var (hintName, content) in additionalGeneratedSources)
        {
            generatedSources.Add((typeof(DependencyInjectionRegistrationGenerator), hintName, SourceText.From(content, Encoding.UTF8)));
        }

        var tester = new VerifyCS.Test
        {
            TestState =
                {
                    Sources = { code }
                },
            ReferenceAssemblies = net8
        };

        foreach (var generatedSource in generatedSources)
        {
            tester.TestState.GeneratedSources.Add(generatedSource);
        }

        tester.ReferenceAssemblies.AddAssemblies(_references);
        tester.TestState.AdditionalReferences.Add(typeof(global::DependencyInjection.SourceGenerator.Contracts.Attributes.RegisterAttribute).Assembly);
        tester.TestState.AdditionalReferences.Add(typeof(global::DependencyInjection.SourceGenerator.LightInject.Contracts.Attributes.RegisterCompositionRootAttribute).Assembly);
        tester.TestState.AdditionalReferences.Add(typeof(global::LightInject.IServiceRegistry).Assembly);
        await tester.RunAsync();
    }

    [Fact]
    public async Task CreateCompositionRoot_RegisterService_NoExistingCompositionRoot()
    {
        var code = """
using DependencyInjection.SourceGenerator.Contracts.Attributes;

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[Register]
public class Service : IService {}
public interface IService {}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service>(new global::LightInject.PerRequestLifeTime());
    }
}
""";

        await RunTestAsync(code, expected);
        Assert.True(true); // silence warnings, real test happens in the RunAsync() method
    }

    [Fact]
    public async Task CreateCompositionRoot_RegisterService_NoExistingCompositionRoot_MultipleRegistrations()
    {
        var code = """
using DependencyInjection.SourceGenerator.Contracts.Attributes;

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[Register(ServiceType = typeof(IService1))]
[Register(ServiceType = typeof(IService2))]
public class Service : IService1, IService2 {}
public interface IService1 {}
public interface IService2 {}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService1, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service>(new global::LightInject.PerRequestLifeTime());
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService2, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service>(new global::LightInject.PerRequestLifeTime());
    }
}
""";

        await RunTestAsync(code, expected);
        Assert.True(true); // silence warnings, real test happens in the RunAsync() method
    }

    [Fact]
    public async Task CreateCompositionRoot_RegisterService_ExistingCompositionRoot()
    {
        var code = """
using DependencyInjection.SourceGenerator.Contracts.Attributes;
using LightInject;

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[Register]
public class Service : IService {}
public interface IService {}

public partial class CompositionRoot : global::LightInject.ICompositionRoot
{
    public static void RegisterServices(global::LightInject.IServiceRegistry serviceRegistry)
    {
        
    } 
}

""";

        var expected = _header + """
public partial class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        RegisterServices(serviceRegistry);
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service>(new global::LightInject.PerRequestLifeTime());
    }
}
""";

        await RunTestAsync(code, expected);
        Assert.True(true); // silence warnings, real test happens in the RunAsync() method
    }

    [Fact]
    public async Task Register_SpecifiedLifetime_And_ServiceName()
    {
        var code = """
using DependencyInjection.SourceGenerator.Contracts.Attributes;
using DependencyInjection.SourceGenerator.Contracts.Enums;

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[Register(Lifetime = Lifetime.Scoped, ServiceName = "Test")]
public class Service : IService {}
public interface IService {}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service>("Test", new global::LightInject.PerScopeLifetime());
    }
}
""";

        await RunTestAsync(code, expected);
        Assert.True(true); // silence warnings, real test happens in the RunAsync() method
    }

    [Fact]
    public async Task Register_Specified_ServiceType()
    {
        var code = """
using DependencyInjection.SourceGenerator.Contracts.Attributes;
using DependencyInjection.SourceGenerator.Contracts.Enums;

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[Register(ServiceType = typeof(Service))]
public class Service : IService {}
public interface IService {}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.Service>(new global::LightInject.PerRequestLifeTime());
    }
}
""";

        await RunTestAsync(code, expected);
        Assert.True(true); // silence warnings, real test happens in the RunAsync() method
    }

    [Fact]
    public async Task Register_NoInteface()
    {
        var code = """
using DependencyInjection.SourceGenerator.Contracts.Attributes;
using DependencyInjection.SourceGenerator.Contracts.Enums;

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[Register]
public class Service {}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.Service>(new global::LightInject.PerRequestLifeTime());
    }
}
""";

        await RunTestAsync(code, expected);
        Assert.True(true); // silence warnings, real test happens in the RunAsync() method
    }

    [Fact]
    public async Task CreateCompositionRoot_DecorateService_NoExistingCompositionRoot()
    {
        var code = """
using DependencyInjection.SourceGenerator.Contracts.Attributes;

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[Decorate]
public class Service : IService {}
public interface IService {}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Decorate<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service>();
    }
}
""";

        await RunTestAsync(code, expected);
        Assert.True(true); // silence warnings, real test happens in the RunAsync() method
    }

    [Fact]
    public async Task RegisterAll_ByInterface()
    {
        var code = """
using global::DependencyInjection.SourceGenerator.Contracts.Attributes;

[assembly: RegisterAll<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService>]

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

public class Service1 : IService {}
public class Service2 : IService {}
public interface IService {}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service2>(new global::LightInject.PerRequestLifeTime());
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service1>(new global::LightInject.PerRequestLifeTime());
    }
}
""";

        await RunTestAsync(code, expected);
    }

    [Fact]
    public async Task CreateCompositionRoot_WithFactoryArguments()
    {
        var code = """
using DependencyInjection.SourceGenerator.Contracts.Attributes;
using System;

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[Register]
public sealed class ReportJob : IReportJob
{
    public ReportJob(IRepository repository, [FactoryArgument] Guid reportId)
    {
    }
}

public interface IRepository {}
public interface IReportJob {}

""";

        var expectedCompositionRoot = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IReportJob, global::DependencyInjection.SourceGenerator.LightInject.Demo.ReportJob>(new global::LightInject.PerRequestLifeTime());
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IReportJobFactory, global::DependencyInjection.SourceGenerator.LightInject.Demo.ReportJobFactory>(new global::LightInject.PerContainerLifetime());
    }
}
""";

        var expectedFactory = """
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public interface IReportJobFactory
{
    global::DependencyInjection.SourceGenerator.LightInject.Demo.IReportJob Create(global::System.Guid reportId);
}

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public sealed class ReportJobFactory : global::DependencyInjection.SourceGenerator.LightInject.Demo.IReportJobFactory
{
    private readonly global::LightInject.IServiceFactory _serviceFactory;

    public ReportJobFactory(global::LightInject.IServiceFactory serviceFactory)
    {
        _serviceFactory = serviceFactory;
    }

    public global::DependencyInjection.SourceGenerator.LightInject.Demo.IReportJob Create(global::System.Guid reportId)
    {
        return (global::DependencyInjection.SourceGenerator.LightInject.Demo.IReportJob)_serviceFactory.GetInstance(typeof(global::DependencyInjection.SourceGenerator.LightInject.Demo.IReportJob), new object[] { reportId });
    }
}
""";

        await RunTestAsync(code, expectedCompositionRoot, ("ReportJobFactory.Factory.g.cs", expectedFactory));
    }

    [Fact]
    public async Task RegisterAll_SpecifyLifetime()
    {
        var code = """
using global::DependencyInjection.SourceGenerator.Contracts.Attributes;
using global::DependencyInjection.SourceGenerator.Contracts.Enums;

[assembly: RegisterAll(typeof(global::DependencyInjection.SourceGenerator.LightInject.Demo.IService<>), Lifetime.Singleton)]

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

public class Service1 : IService<string> {}
public class Service2 : IService<int> {}
public interface IService<T> {}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService<int>, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service2>(new global::LightInject.PerContainerLifetime());
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.IService<string>, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service1>(new global::LightInject.PerContainerLifetime());
    }
}
""";

        await RunTestAsync(code, expected);
    }

    [Fact]
    public async Task RegisterAll_ByBaseType_WithServiceName()
    {
        var code = """
using global::DependencyInjection.SourceGenerator.Contracts.Attributes;

[assembly: RegisterAll<global::DependencyInjection.SourceGenerator.LightInject.Demo.MyBase>(IncludeServiceName = true)]

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

public class Service1 : MyBase {}
public class Service2 : MyBase {}
public abstract class MyBase {}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.MyBase, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service2>("Service2", new global::LightInject.PerRequestLifeTime());
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.MyBase, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service1>("Service1", new global::LightInject.PerRequestLifeTime());
    }
}
""";

        await RunTestAsync(code, expected);
    }

    [Fact]
    public async Task RegisterAll_ByBaseType_WithoutServiceName()
    {
        var code = """
using global::DependencyInjection.SourceGenerator.Contracts.Attributes;

[assembly: RegisterAll<global::DependencyInjection.SourceGenerator.LightInject.Demo.MyBase>]

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

public class Service1 : MyBase {}
public class Service2 : MyBase {}
public abstract class MyBase {}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.MyBase, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service2>(new global::LightInject.PerRequestLifeTime());
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.MyBase, global::DependencyInjection.SourceGenerator.LightInject.Demo.Service1>(new global::LightInject.PerRequestLifeTime());
    }
}
""";

        await RunTestAsync(code, expected);
    }

    [Fact]
    public async Task RegisterCompositionRoot()
    {
        var code = """
using global::DependencyInjection.SourceGenerator.LightInject.Contracts.Attributes;
using LightInject;

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[RegisterCompositionRoot]
public class CustomCompositionRoot : ICompositionRoot
{
    public void Compose(IServiceRegistry serviceRegistry)
    {
    }

}

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.RegisterFrom<global::DependencyInjection.SourceGenerator.LightInject.Demo.CustomCompositionRoot>();
    }
}
""";

        await RunTestAsync(code, expected);
    }

    [Fact]
    public async Task RegisterRecord()
    {
        var code = """

using DependencyInjection.SourceGenerator.Contracts.Attributes;

namespace DependencyInjection.SourceGenerator.LightInject.Demo;

[Register]
public record Service();

""";

        var expected = _header + """
public class CompositionRoot : global::LightInject.ICompositionRoot
{
    public void Compose(global::LightInject.IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<global::DependencyInjection.SourceGenerator.LightInject.Demo.Service>(new global::LightInject.PerRequestLifeTime());
    }
}
""";

        await RunTestAsync(code, expected);
    }
}