// <auto-generated/>
#pragma warning disable
#nullable enable
namespace Microsoft.Extensions.DependencyInjection;
using global::Microsoft.Extensions.DependencyInjection;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static partial class ServiceCollectionExtensions
{
    public static partial string AddTestProject(this string services)
    {
        return services;
    }
}

internal static partial class ServiceCollectionExtensions
{
    public static partial string AddTestProject(this string services);
}